kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: lizheming/drone-deta
    auto_tag: true
  when:
    event: tag
    branch:
    - master